### PR TITLE
refactor: use Class for ks cache to highly improve performance

### PR DESCRIPTION
**Pull request by Maples7**
People do not only use `ks` once for all. Its performance can be improved by avoid repeated calculation of `ks`.

### CODE REVIEW

**Comment by morganherlocker** [comment]
Awesome contribution. Do you happen to know how big of a speed up this is?

**Comment by Maples7** [comment]
It depends on how many times `ks` can be reused I think. Also, we can do some benchmark by assuming a possible average number.

**Comment by Maples7** [comment]
For reference only:

Old way:
```js
var spline = require('.');

var xs = [1, 2, 3, 4, 5];
var ys = [9, 3, 6, 2, 4];

var time1 = new Date().getTime();

for (var j = 0; j < 100; j++) {
  for (var i = 0; i < 50; i++) {
    spline(i * 0.1, xs, ys);
  }
}

var time2 = new Date().getTime();
console.log(time2 - time1); // around 24ms 
```

New way:
```js
var Spline = require('.');

var xs = [1, 2, 3, 4, 5];
var ys = [9, 3, 6, 2, 4];

var time1 = new Date().getTime();
const spline = new Spline(xs, ys);

for (var j = 0; j < 100; j++) {
  for (var i = 0; i < 50; i++) {
    spline.at(i * 0.1);
  }
}

var time2 = new Date().getTime();
console.log(time2 - time1); // around 6ms 
```

On my own computer `2.4 GHz Intel Core i7`.

**Comment by morganherlocker** [comment]
These changes were published under v2.0.0. Thanks for the contribution @Maples7!

**Pull request merged**
